### ISSUE TITLE
Update workflow fails everytime.

### ISSUE THREAD

**Issue by rinx** [vdaas/vald-client-clj#18]
Because the new maven API returns 301, update workflow fails everytime.
Please add a `-L` option to the curl command.

```sh
curl -sL
```
https://github.com/vdaas/vald-client-clj/blob/c5009ed631dfca81180b325b9a176ee284ed0c78/.github/workflows/update.yml#L26

**Comment by vankichi** [comment]
sorry for late reply and thank you for inform us.
we'll fix in near future.
